import {Constants } from '../common-module/Constants';
import { stat } from 'fs';

export class DataEntryApi {
    // companySearchUrl url used for Provider-Search & batch-search becoz we don't have service yet. 
    static companySearchUrl = Constants.baseUrl + 'company-service/companySearch';
    
    /* get API*/ 
    static getAutoGeneratedClaimNumberUrl= Constants.baseUrl + 'ahc-service/autoGenrateClaimNumber';
    static getAutoGeneratedClaimItemNumberUrl= Constants.baseUrl + 'ahc-service/autoGenrateItemNumber';
    static getServiceCode= Constants.baseUrl + 'ahc-service/predictiveServiceCode';
    static getToothCode= Constants.baseUrl + 'ahc-service/getToothCodeList';
    static getSkillCode= Constants.baseUrl + 'ahc-service/getSkillCodeList';
    static getFunctionCentre= Constants.baseUrl + 'ahc-service/getFunctionalCentreList';
    static getDignosticPrimary= Constants.baseUrl + 'ahc-service/predictiveDiagnosticCode';
    static getLatestBatchNumAndKey= Constants.baseUrl + 'ahc-service/getLatestBatchNumAndKey';
    static addClaimToBatchUrl = Constants.baseUrl + 'ahc-service/addClaimToBatch';
    static getAhcClaim = Constants.baseUrl +'ahc-service/getAhcClaim';
    static deleteAhcClaim = Constants.baseUrl +'ahc-service/deleteAhcClaim';

    static updateBatchClaim = Constants.baseUrl +'ahc-service/updateBatchClaim';
    static generateBatchFile = Constants.baseUrl +'ahc-service/generateBatchFile';
    static getClaimListByBatchNumber = Constants.baseUrl +'ahc-service/getClaimListByBatchNumber';
    static downloadBatchFile = Constants.baseUrl +'ahc-service/batchFileUrl';
    static getFeeModifier = Constants.baseUrl +'ahc-service/searchFeeModifier';
    static deleteClaimItemAhcUrl = Constants.baseUrl +'ahc-service/deleteClaimItemAhc';

    static getDisciplineTypeList = Constants.baseUrl +'claim-service/getDisciplineList';
    static saveServiceProviderBillAddUrl = Constants.baseUrl + 'claim-service/saveServiceProviderBillAdd';
    static getServiceProviderBillAddListUrl = Constants.baseUrl + 'claim-service/getServiceProviderBillAddList';
    static saveProviderApprovalUrl = Constants.baseUrl + 'claim-service/saveProviderApproval';
    static saveServiceProviderSpecialtyUrl = Constants.baseUrl + 'claim-service/saveServiceProviderSpecialty';
    static getSpecialityBasedOnDisciplineUrl = Constants.baseUrl + 'claim-service/getSpecialityBasedOnDiscipline';
    static getSpecialityAssgnListByProviderIdUrl = Constants.baseUrl + 'claim-service/getSpecialityAssgnListByProviderId';
    static getServiceProviderEligibilityBasedOnProviderUrl = Constants.baseUrl + 'claim-service/getServiceProviderEligibilityBasedOnProvider';

    static getAhcClaimItemListUrl = Constants.baseUrl + 'ahc-service/getAhcClaimItemList';
    static getAhcClaimItemUrl = Constants.baseUrl + 'ahc-service/getAhcClaimItem';
    static updateClaimItemInBatchUrl = Constants.baseUrl + 'ahc-service/updateClaimItemInBatch';
    static addClaimItemInBatchUrl = Constants.baseUrl + 'ahc-service/addClaimItemInBatch';
    static getAhcDisciplineUrl = Constants.baseUrl + 'ahc-service/getAhcDiscipline';

    static getFeeModifierListUrl = Constants.baseUrl + 'ahc-service/getFeeModifierList';
    static predictiveDentistULISearch = Constants.baseUrl + 'ahc-service/getPredictiveProviderUli';

    
    /** Dentist Info Api */

    static saveProvider= Constants.baseUrl + 'ahc-service/saveProvider';
    static getProviderDetails= Constants.baseUrl + 'ahc-service/getProviderDetails';
    static saveProviderAddress= Constants.baseUrl + 'ahc-service/saveProviderAddress';
    static editProviderAddress= Constants.baseUrl + 'ahc-service/editProviderAddress';
    static ValidateUli= Constants.baseUrl + 'ahc-service/getUliValidation';
    static getProviderAddressByKey= Constants.baseUrl + 'ahc-service/getProviderAddressByKey';
    static getProviderAddressListByProvKey= Constants.baseUrl + 'ahc-service/editProviderAddress';
    static validateDentist = Constants.baseUrl + 'ahc-service/getProviderPostalCode'
    static getDentistBan = Constants.baseUrl + 'ahc-service/getProviderBAN'
    static validatePatientHc = Constants.baseUrl + 'ahc-service/claimPhnValidate'
    static validateSurfaceTextUrl = Constants.baseUrl + 'claim-service/checkToothSurfaceCombo';
    /** End */

     /* get Search Api */
    static getProviderSearchList=Constants.baseUrl + 'ahc-service/providerSearchResult';
    static getBatchSearchList=Constants.baseUrl + 'ahc-service/getBatchSearchList';
    static uploadReportingFile = Constants.baseUrl + 'ahc-service/importADSCBatch';
    static getAhcUsersList = Constants.baseUrl + 'ahc-service/getAhcUsersList';
    static updatePassword = Constants.baseUrl + 'ahc-service/changePassword';
    static getExplanatoryCodeListUrl =  Constants.baseUrl + 'ahc-service/getExplanatoryCodeList';
    static getExplanatoryCodeUrl =  Constants.baseUrl + 'ahc-service/getExplanatoryCode';

    /* Reports API 13-Aug-2020*/
    static getProductionReportUrl = Constants.baseUrl + 'ahc-service/getProductionReport'
    static getSubmissionReportUrl = Constants.baseUrl + 'ahc-service/getSubmissionReport'
    static sendReportMailUrl = Constants.baseUrl + 'ahc-service/sendReportMail'

    /* importBatchBalance API */ 
    static importBatchBalanceUrl = Constants.baseUrl + 'ahc-service/importBatchBalance'

    /* Log #1093 */
    static getDiagnosticCodListUrl = Constants.baseUrl + 'ahc-service/getDiagnosticCodList' 
    // Log #1105
    static checkDigitCodeUrl = Constants.baseUrl + 'ahc-service/checkDigit'
    // log 1116
    static getProviderSpecialityList= Constants.baseUrl + 'ahc-service/getProviderSpecialityList';
    static importProvidersData= Constants.baseUrl + 'ahc-service/importProvidersData';

}
